version: 2
jobs:
  build:
    docker:
      - image: cimg/base:2024.11
    environment:
      
    steps:
      - checkout
      - setup_remote_docker
      - run: 
          name: Build Docker Image
          command: |
            set +x -e
            wget https://github.com/tcnksm/ghr/releases/download/v0.16.0/ghr_v0.16.0_linux_amd64.tar.gz
            tar -zxvf ghr_v0.16.0_linux_amd64.tar.gz
            mv ghr_v0.16.0_linux_amd64/ghr ./ghr
            rm -rf ghr_v0.16.0_linux_amd64
            chmod +x ghr
            ./ghr --version
            export DOCKER_CLI_EXPERIMENTAL=enabled
            export DOCKER_BUILDKIT=1
            TAG=0.1.$CIRCLE_BUILD_NUM
            mkdir -p ~/.docker/cli-plugins/
            curl --silent -L --output ~/.docker/cli-plugins/docker-buildx https://github.com/docker/buildx/releases/download/v0.11.2/buildx-v0.11.2.linux-amd64
            chmod a+x ~/.docker/cli-plugins/docker-buildx
            docker run --rm --privileged linuxkit/binfmt:a17941b47f5cb262638cfb49ffc59ac5ac2bf334
            docker context create multi-arch-build
            docker buildx create --use multi-arch-build --platform linux/arm/v7,linux/arm64/v8,linux/amd64
            ADDITIONAL_PARAMETERS=""
            if [ "${CIRCLE_BRANCH}" == "main" ]; then
              ADDITIONAL_PARAMETERS="--push"
              echo $DOCKERPASS | docker login --username $DOCKERLOGIN --password-stdin
            fi
            docker buildx build $ADDITIONAL_PARAMETERS --platform linux/arm/v6,linux/arm/v7,linux/arm64/v8,linux/amd64 -t msroest/sabnzbd_exporter:latest -t msroest/sabnzbd_exporter:$TAG .
            
            docker images
            if [ "${CIRCLE_BRANCH}" == "main" ]; then
              ./ghr -generatenotes -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${TAG}
            fi
            